### ISSUE TITLE
Reducer incoming state not optional?

### ISSUE THREAD

**Issue by nuke-dash** [ReSwift/ReactiveReSwift#9]
What is the reason behind the Reducer's incoming state not being optional?
According to Redux the incoming states can be undefined and then it is up to the reducers to supply an initial state.
http://redux.js.org/docs/basics/Reducers.html
It also seems that ReSwift itself has an optional state for their reducers.
https://github.com/ReSwift/ReSwift/blob/master/ReSwift/CoreTypes/Reducer.swift

If the state can be nil the initial state value can be supplied by the reducers individually.
Then you would not need to bother with creating an initial state object that has all its substates filled in.

**Comment by Qata** [comment]
State not being `Optional` is an intentional design decision meant to force the user's hand into creating an `initialState` object that can easily be inspected for all of its initial values. This is meant to evoke Elm's style of state. 

That being said, your point made me realise that you can't create an `Optional` state explicitly without conforming `Optional` to `StateType`, so I'll be removing `StateType` in the next release so that you can have container based state.

**Comment by nuke-dash** [comment]
Thanks for the clarification
